logger:

    # Logger settings
    # Logs specific actions pertaining to souls

    # Enable/Disable this feature entirely
    enabled: true

    log-soul-spawns: true # Log soul spawns (when a soul is created)
    log-soul-pickups: true # Log soul pickups (when they are picked up by the player)
    log-soul-explosions: true # Log soul explosions (otherwise known as when they disappear)

    # Log format

    # Placeholders:
    # {soulOwner} for soul owner (player)
    # {x} for x coordinate
    # {y} for y coordinate
    # {z} for z coordinate
    # {world} for world name, configure world name aliases before for readability

    log-soul-spawns-message: "&7[SoulTracker] &aSoul spawned for &e{soulOwner}&a at &e{x} {y} {z} &ain &e{world}"
    log-soul-pickups-message: "&7[SoulTracker] &e{soulOwner}&a picked up a soul at &e{x} {y} {z} &ain &e{world}"
    log-soul-explosions-message: "&7[SoulTracker] &cSoul for &e{soulOwner}&c exploded at &e{x} {y} {z} &cin &e{world}"


hologram:

    # Hologram settings
    # Holograms are displayed above the soul's grave

    # Enable/Disable this feature entirely
    enabled: true

    # Enable/Disable hologram persistence
    # If enabled, holograms will persist through server restarts
    persistence: false

    # Configure the location of the hologram relative to the soul's location
    x-offset: 0.0
    y-offset: 3.5
    z-offset: 0.0

    # Scale of the hologram (x,y,z)
    scale: "1.0,1.0,1.0"

    # Billboard setting (CENTER, FIXED, HORIZONTAL, VERTICAL)
    billboard: "CENTER"

    # Text alignment (CENTER, LEFT, RIGHT)
    text-alignment: "CENTER"
    
    # See through blocks?
    see-through: false

    # Configure the background
    custom-background: false
    background-color: "1,100,255,79" # ARGB format

    # Configure the text shadow
    text-shadow: false 
    
    # Shadow details (Only applies if text-shadow is true)
    shadow-radius: 0
    shadow-strength: 1.0

    # Configure the text of the hologram, using MiniMessage and/or Legacy Formatting

    # Placeholders:
    # {soulOwner} for soul owner (player)
    # {soulFormattedDeathTime} for when the soul was created (when the player died)
    # {soulRawDeathTime} for when the soul was created - when the player died (in milliseconds)
    # {soulFormattedExpireTime} for when the soul will expire
    # {soulRawExpireTime} for when the soul will expire (in milliseconds)
    # {soulFormattedTimeLeft} for how long the soul has left until it expires and explodes
    # {soulRawTimeLeft} for how long the soul has left until it expires and explodes (in milliseconds)
    # {soulInventoryAmount} for the amount of items in the soul's inventory (number of stacks)
    # {soulExperienceAmount} for the amount of experience in the soul's inventory
    lines:
        - ""
        - "&b☠ &lSOUL GRAVE&r &8» &f{soulOwner}"
        - "&7Passed away at &f{soulFormattedDeathTime}"
        - ""
        - "&b [ᴛᴏᴜᴄʜ ᴛʜᴇ ɢʀᴀᴠᴇ ᴛᴏ ʀᴇᴛʀɪᴇᴠᴇ ᴇꜱꜱᴇɴᴄᴇ] &r"
        - ""

    # How frequent should we update the holograms in ticks? Default: 10 (0.5 seconds)
    update-ticks: 10

death-coordinates:

    # Death Coordinate settings
    # This feature sends soul coordinates to the players' chat when they die.

    # Enable/Disable this feature entirely
    enabled: true

    # Configure the text of the death coordinates message, using MiniMessage and/or Legacy Formatting
    # Placeholders:
    # {soulOwner} for soul owner (player)
    # {x} for x coordinate
    # {y} for y coordinate
    # {z} for z coordinate
    # {world} for world name, configure world name aliases before for readability

    message: "&c☠ Your soul has spawned at &f{x} {y} {z}&c in the &f{world}"


options:

    # Date format
    date-format: "yyyy-MM-dd HH:mm:ss"

    # Time format
    # {d} for days, {h} for hours, {m} for minutes, {s} for seconds, {x} for milliseconds
    time-format: "{m}:{s}:{x}"

    world-name-aliases:
        # World name aliases
        # This is used to display the world name in a more readable format
        # For example, "world_nether" can be displayed as "Nether"
        # This is case-sensitive and should match the world name exactly
        # The key is the world name, the value is the alias
        # Example: "world_nether": "Nether"
        world: "Overworld"
        world_nether: "Nether"
        world_the_end: "End"
        resource_world: "Resource World"
        spawn: "Spawn"
